const types = {
  FETCH_RESTAURANTS: "FETCH_RESTAURANTS",
  FETCH_RESTAURANT: "FETCH_RESTAURANT",
  CREATE_RESTAURANT: "CREATE_RESTAURANT",
  EDIT_RESTAURANT: "EDIT_RESTAURANT",
  DELETE_RESTAURANT: "DELETE_RESTAURANT",
};

export default types;
