const types = {
  SELECT_RESTAURANT: "SELECT_RESTAURANT",
  SELECT_MENU: "SELECT_MENU",
  FETCH_RESTAURANTS: "FETCH_RESTAURANTS",
  FETCH_RESTAURANT: "FETCH_RESTAURANT",
  CREATE_RESTAURANT: "CREATE_RESTAURANT",
  EDIT_RESTAURANT: "EDIT_RESTAURANT",
  DELETE_RESTAURANT: "DELETE_RESTAURANT",
  FETCH_MENUS: "FETCH_MENUS",
  FETCH_MENU: "FETCH_MENU",
  CREATE_MENU: "CREATE_MENU",
  EDIT_MENU: "EDIT_MENU",
  DELETE_MENU: "DELETE_MENU",
  FETCH_ITEMS: "FETCH_ITEMS",
  FETCH_ITEM: "FETCH_ITEM",
  CREATE_ITEM: "CREATE_ITEM",
  EDIT_ITEM: "EDIT_ITEM",
  DELETE_ITEM: "DELETE_ITEM",
};

export default types;
